# Generated by Django 6.0.5 on 2026-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eixotematico_aluno_coordenador_orgacademica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='alunos_participantes',
            field=models.ManyToManyField(blank=True, related_name='atividades_internas', to='core.aluno'),
        ),
    ]
