# Generated by Django 6.0.5 on 2026-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividadecomplementar_alunos_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ABERTA', 'Aberta'), ('VALIDADO', 'Validado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
