# Generated by Django 6.0.5 on 2026-06-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_atividadecomplementar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='caminho_comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
