# Generated by Django 6.0.5 on 2026-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_atividadecomplementar_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='atividadecomplementar',
            name='palestrante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
