# Generated by Django 6.0.5 on 2026-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atividadecomplementar_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='data_hora_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
